ThinLineIT/CtrlF_Backend

- django_girls_tutorial/step2/jingu/djangogirls/blog/api/views.py
- django_girls_tutorial/step2/jingu/djangogirls/blog/tests.py
1. publish 코드 추가
slack 참고해서 publish 코드 추가
```
self._create_post(
author=self.author, title=f"test title-{i}", text=f"test text-{i}"
)
```
=>
```
self._create_post(
author=self.author, title=f"test title-{i}", text=f"test text-{i}"
).publish()
```
2. 테스트 결과
> Add retrieve_post_list API

- .gitignore
- django_girls_tutorial/step2/sehwa/djangogirls/blog/api/urls.py
- django_girls_tutorial/step2/sehwa/djangogirls/blog/api/views.py
- django_girls_tutorial/step2/sehwa/djangogirls/blog/tests.py
- django_girls_tutorial/step2/sehwa/djangogirls/blog/views.py
* Test 성공.
* test에서 response status를 OK->200, NOT_FOUND->404 로 변경.
> retrieve_post_detail 구현 및 테스트

- django_girls_tutorial/step2/jingu/djangogirls/blog/api/urls.py
- django_girls_tutorial/step2/jingu/djangogirls/blog/api/views.py
- django_girls_tutorial/step2/jingu/djangogirls/blog/tests.py
1. test.py status code OK, NOT_FOUND 각각 200, 404로 변경
2. 테스트 결과
> Add retrieve_post_detail API

- django_girls_tutorial/step2/jinho/djangogirls/blog/api/views.py
> add retrieve_post_detail method

- django_girls_tutorial/step2/jingu/djangogirls/blog/api/views.py
- django_girls_tutorial/step2/jingu/djangogirls/blog/tests.py
> Add Post API

- .gitignore
- django_girls_tutorial/step2/sehwa/djangogirls/blog/api/views.py
* `retrieve_post_detail`는 제외하고 테스트.
> Add create_post and update_post_with_put

- v2/README.md
> Add Doc check email dupliacate

- django_girls_tutorial/step2/sehwa/djangogirls/blog/api/urls.py
- django_girls_tutorial/step2/sehwa/djangogirls/blog/api/views.py
- django_girls_tutorial/step2/sehwa/djangogirls/blog/tests.py
0. 조건
* post id와 author id를 받는다.
1. 성공
* post id에 해당하는 post가 삭제되고 200 return.
2. 실패
1. post id 가 유효하지 않을 때.
* status code: 403
* message: post를 찾을 수 없습니다.
2. author id와 post의 author id가 일치하지 않을 때.
* status code: 403
* message: 유효하지 않은 사용자 id입니다.
> Add delete_post API and Test

- .github/workflows/checks.yml
- poetry.lock
- pyproject.toml
- v2/src/config/settings/base.py
- v2/src/ctrlf_auth/serializers.py
> TH-69 fix cors error

- v2/src/ctrlf_auth/admin.py
> TH-77 add admin related code

- v2/mock_api/src/config/api.py
TH-79 add note list count in mock not list api
close #79
> TH-79 add note list count in mock not list api

- v2/src/ctrlf_auth/urls.py
- v2/src/ctrlf_auth/views.py
TH-81 add temp deleting email api
> TH-81 add temp deleting email api

- v2/mock_api/src/config/api.py
- v2/mock_api/src/config/schema.py
TH-83 add mock api about check verification code
> TH-83 add mock api about check verification code

- v2/src/ctrlf_auth/serializers.py
- v2/src/ctrlf_auth/urls.py
- v2/src/ctrlf_auth/views.py
- v2/src/tests/test_auth.py
> SH-19 Add check email duplicate api

- v2/src/ctrlf_auth/serializers.py
- v2/src/ctrlf_auth/urls.py
- v2/src/ctrlf_auth/views.py
- v2/src/tests/test_auth.py
1. 닉네임 유효성 검사
* 영어,숫자,한글 2~10자
* 공백x
* 특수문자x
* `Serializer`의 `RegexField` 사용
> JH-75 check nickname validation

- v2/src/ctrlfbe/admin.py
- v2/src/ctrlfbe/apps.py
- v2/src/ctrlfbe/models.py
> TH-73 add note model

- v2/mock_api/src/config/api.py
- v2/mock_api/src/config/schema.py
> TH-92 add mock api about note detail first step

- v2/src/ctrlf_auth/authentication.py
- v2/src/ctrlf_auth/constants.py
- v2/src/ctrlf_auth/urls.py
- v2/src/tests/test_auth.py
성공 케이스에 해당하는 authentication 모듈만 추가해두었습니다
> TH-24 add jwt authentication module

- v2/src/common/exceptions.py
- v2/src/config/settings/base.py
- v2/src/ctrlf_auth/authentication.py
- v2/src/ctrlf_auth/views.py
- v2/src/tests/test_auth.py
> TH-24 add 401 case in authentication class

- v2/src/ctrlf_auth/views.py
- v2/src/tests/test_auth.py
login response에 user_id를 내려주도록 합니다
> TH-103 feat: add user_id in login response

- v2/mock_api/src/config/api.py
- v2/mock_api/src/config/schema.py
> TH-109 add mock apis on issue note topic

- v2/mock_api/src/config/api.py
- v2/mock_api/src/config/schema.py
> TH-113 add page list api

- setup.cfg
- v2/mock_api/src/config/api.py
- v2/mock_api/src/config/constants.py
- v2/mock_api/src/config/schema.py
TH-103 feat: add retrieve_page_list api
> TH-103 feat: add retrieve_page_list api

- v2/mock_api/src/config/api.py
- v2/mock_api/src/config/schema.py
> SH-126: Page detail mock API

- v2/src/config/urls.py
- v2/src/ctrlfbe/constants.py
- v2/src/ctrlfbe/page_urls.py
- v2/src/ctrlfbe/swagger.py
- v2/src/ctrlfbe/test.py
- v2/src/ctrlfbe/views.py
`page_id`를 받아 해당 페이지의 정보를 반환하는 API 입니다.
#131
> SH-131: page detail api

- v2/src/ctrlf_auth/helpers.py
- v2/src/ctrlf_auth/serializers.py
- v2/src/ctrlf_auth/swagger.py
- v2/src/ctrlf_auth/views.py
- v2/src/tests/test_auth.py
close #143 
자세한 내용은 143 번 티켓 참고해주세요!
> TH-143: add signing token in response for sending verification code by email

- v2/src/ctrlfbe/serializers.py
- v2/src/tests/test_issues.py
TH-179: add legacy_title field in issue detail
> TH-179: add legacy_title field in issue detail

- v2/src/common/exceptions.py
- v2/src/ctrlfbe/basedata.py
- v2/src/ctrlfbe/issue_urls.py
- v2/src/ctrlfbe/note_urls.py
- v2/src/ctrlfbe/page_urls.py
- v2/src/ctrlfbe/paginations.py
- v2/src/ctrlfbe/serializers.py
- v2/src/ctrlfbe/swagger.py
- v2/src/ctrlfbe/topic_urls.py
- v2/src/ctrlfbe/views.py
- v2/src/tests/test_note.py
- v2/src/tests/test_topics.py
APIView 쓰던 class들 ViewSet으로 통합
중복 코드 일부 수정
Pagination class 추가
> JH-165: Refactoring

- v2/src/ctrlf_auth/constants.py
- v2/src/ctrlf_auth/serializers.py
- v2/src/ctrlf_auth/views.py
- v2/src/tests/test_auth.py
> TH-195: fix email verification code validate part

- v2/src/ctrlf_auth/constants.py
- v2/src/ctrlf_auth/serializers.py
- v2/src/ctrlf_auth/views.py
- v2/src/ctrlfbe/issue_urls.py
- v2/src/ctrlfbe/serializers.py
- v2/src/ctrlfbe/swagger.py
- v2/src/ctrlfbe/views.py
- v2/src/tests/test_auth.py
- v2/src/tests/test_issues.py
> TH-197: add issue count api

- v2/src/ctrlfbe/paginations.py
- v2/src/ctrlfbe/views.py
- v2/src/tests/test_issues.py
TH-199: Fix: Add IssueList filtering about Requested and Rejected
> TH-199: Fix: Add IssueList filtering about Requested and Rejected

- v2/src/ctrlfbe/views.py
TH-199: Fix: Override self.queryset for fixing bug
> TH-199: Fix: Override self.queryset for fixing bug

- v2/src/ctrlfbe/page_urls.py
TH-0 Fix: Change url path order
> TH-0: Fix: Change url path order

- v2/src/ctrlfbe/models.py
- v2/src/ctrlfbe/views.py
지옥같던 Issue Approve view를 리팩토링 해봄.. 완벽하게 한건 아니지만 그전 보단 나아진걸로 보임..
> TH-204: Refactor: Refactor Issue Approve view
